// 사이드바(LNB) 메뉴 정의.
//
// 실제 톡스 LMS 관리자 페이지의 전체 메뉴 구조를 그대로 옮겨왔다(화면 껍데기만).
// 대부분의 하위 메뉴는 이 프로젝트 범위 밖의 기능이라 클릭해도 아무 동작을
// 하지 않는 "표시용" 항목이며(path 없음), 실제로 동작하는 화면은 "교육상품관리"
// 대메뉴의 "교재상품관리" 항목 아래에 있는 3개 화면(교재 주문 대시보드 /
// 교재주문·재고관리 / 주문취소·반품관리)뿐이다.
//
// 새 화면을 실제로 추가할 때는: 해당 항목에 path를 넣고, App.jsx의 <Routes>에
// 대응하는 <Route>를 등록하면 된다.
export const MENU_TREE = [
  { key: 'messenger', label: '톡톡메신저', icon: '💬' },
  { key: 'oldsite', label: '이전사이트보기', icon: '🔍' },
  {
    key: 'family-site',
    label: 'Family Site',
    icon: '🏢',
    children: [
      { label: 'Training School' },
      { label: 'Performance Statistics' },
      { label: '수업불편 및 요청상담' },
      { label: 'Training Center(Tutor)' },
      { label: 'Training Center(Staff)' },
      { label: 'New Tutor Lounge' },
      { label: 'Basic Grammar Test' },
      { label: '업무공유센터' },
      { label: '통합LMS' },
      { label: '311English' },
      { label: '유입접속통계' },
      { label: '아이딕 잉글리쉬 수강회원' },
      { label: '아이딕 잉글리쉬 퇴원회원' },
      { label: '아이딕 잉글리쉬 휴원회원' },
      { label: 'Re-enrollment Statistics' },
      { label: '25 초청강사 회원리스트' },
      { label: '국제학교 LMS' },
      { label: '세부어학원' },
      { label: 'TSA LMS' },
    ],
  },
  {
    key: 'member',
    label: '회원관리',
    icon: '👥',
    children: [{ label: '회원리스트' }, { label: '결합상품 회원리스트' }, { label: '회원가입 무료체험 통계' }],
  },
  {
    key: 'cs-consult',
    label: '고객센터 상담문의',
    icon: '👥',
    children: [
      { label: '고객센터 상담리스트' },
      { label: '자주쓰는 답변관리' },
      { label: '고객센터 상담통계' },
      { label: '상담 담당자 리스트' },
      { label: '고객센터 채팅설정' },
    ],
  },
  {
    key: 'covid',
    label: '코로나 비상대응',
    icon: '🦠',
    children: [
      { label: '코로나 대체수업 신청 리스트' },
      { label: '코로나 대체강사 설문조사' },
      { label: '코로나 대체수업 리스트' },
      { label: '코로나 대체회원 목록' },
      { label: '수업 일일통계' },
      { label: '대체강사 신청통계' },
      { label: '정규수업 변경신청' },
    ],
  },
  {
    key: 'idic-tab',
    label: '아이딕탭 관리',
    icon: '📱',
    children: [{ label: '아이딕탭 구매내역' }, { label: '아이딕탭 구매내역 - 쿠폰' }],
  },
  {
    key: 'class-apply',
    label: '수강신청관리',
    icon: '📄',
    children: [
      { label: '수강신청목록' },
      { label: '수강중회원목록' },
      { label: '완료목록' },
      { label: '취소목록' },
      { label: '재수강 확인 리스트' },
      { label: '수강시작목록' },
      { label: '수강종료목록' },
      { label: '장기연기목록' },
      { label: '보강권관리' },
      { label: '결석관리' },
      { label: '일일수강평가목록' },
      { label: '카드/실시간/무통장 결제확인' },
      { label: '자동재수강' },
      { label: '6개월이상수강중회원' },
      { label: '원서수업 신청내역' },
      { label: '방학 특강 신청자' },
      { label: '이벤트 신청자' },
      { label: '이벤트 관리' },
      { label: '월별수강변경사항' },
      { label: '특강권 지급 목록' },
      { label: '수강 신청 시 보카킹 신청 리스트' },
      { label: '학습 과정 통계' },
      { label: '스토리 라이팅 상담 리스트' },
    ],
  },
  { key: 'vocaking', label: '보카킹 관리', icon: '📚' },
  {
    key: 'new-tutor-eval',
    label: '신규강사 수업 평가',
    icon: '💳',
    children: [
      { label: '체험수업 신청자 List' },
      { label: '강사 평가 목록(회원)' },
      { label: '강사 평가 목록(매니저)' },
      { label: '강사 평가 통계' },
      { label: '신규강사 퇴사 관리' },
    ],
  },
  {
    key: 'free-class',
    label: '무료체험관리',
    icon: '📊',
    children: [
      { label: '무료체험 통계' },
      { label: '무료체험 카렌다' },
      { label: 'LAT Monitoring' },
      { label: 'LAT Tutor Monitoring' },
      { label: 'Enrolled Rate Board' },
      { label: '무료체험 신청목록' },
      { label: '무료체험 유입통계' },
      { label: '아이딕탭 무료체험 신청자 배송정보' },
      { label: '무료체험 가배정표' },
      { label: '취소/미수강목록' },
      { label: '무료체험 자동배정' },
      { label: '무료체험 미신청 목록' },
      { label: 'LAT 캐릭터관리' },
      { label: 'LAT 캐릭터레벨관리' },
      { label: 'Online LAT Result' },
      { label: '1:1 Final LAT Result' },
    ],
  },
  {
    key: 'timetable',
    label: '시간표관리',
    icon: '🕐',
    children: [
      { label: '강사결근 처리목록' },
      { label: '단체 연기 / 대체 수업 리스트' },
      { label: '원어민 강사 시간표' },
      { label: '아이딕 강사 시간표' },
      { label: '시간표 검색' },
      { label: '성향별 검색 기능' },
      { label: '시간별 강사 수업 통계 (2~6시)' },
      { label: '시간별 강사 수업 통계 (6~9시)' },
      { label: '시간별 강사 수업 통계 (9~12시)' },
      { label: '보카킹 강사 시간표' },
    ],
  },
  {
    key: 'cs-study',
    label: 'CS, 학습상담 관리',
    icon: '👥',
    children: [
      { label: '일일수강평가목록' },
      { label: '퇴사강사케어콜관리' },
      { label: '월별수강변경사항' },
      { label: '강사요청목록' },
      { label: 'New Student Alert' },
      { label: '강사요청목록 통계' },
      { label: '학습 매니저 퇴원생 관리' },
      { label: '강사 변경 회원 리스트' },
      { label: '강사공지사항' },
      { label: '선생님 사랑해요' },
      { label: '회원상담노트' },
      { label: '상담노트 카테고리관리' },
      { label: 'MO LIST' },
      { label: 'M.E Translation' },
      { label: 'Before & After 영상' },
      { label: 'Q & A' },
      { label: '퇴원사유 설문조사' },
      { label: '화상강의실 원격 요청 리스트' },
      { label: '설치확인 리스트' },
      { label: '회원 OS 버전확인' },
    ],
  },
  { key: 'dfb-voca', label: 'DFB VOCA LIST', icon: '🚩', children: [{ label: 'VOCA Homework List' }] },
  {
    key: 'tutors-page',
    label: "Tutor's Page",
    icon: '🚩',
    children: [
      { label: 'All TS Tutors' },
      { label: '강사성향 평가현황' },
      { label: '강사평가 대분류설정' },
      { label: '강사평가 소분류설정' },
      { label: 'Tag 관리' },
      { label: '레벨링 체크리스트 관리' },
    ],
  },
  { key: 'talks-diary', label: "Talk's Diary", icon: '🚩' },
  {
    key: 'dropped',
    label: 'Dropped Students',
    icon: '🔔',
    children: [
      { label: 'Dropped Students List' },
      { label: 'Monthly Rate of the Dropped' },
      { label: '퇴원생목록' },
      { label: '퇴원사유 설문조사' },
      { label: '불만퇴원생 목록' },
      { label: '퇴원생 통계' },
    ],
  },
  {
    key: 'integrated-control',
    label: '통합관제시스템',
    icon: '📈',
    children: [
      { label: '일일수업통계' },
      { label: '강사 월별 전체 퇴원생 현황' },
      { label: '강사 월별 첫달 퇴원생 현황' },
      { label: '퇴원생 현황' },
      { label: '문제강사확인' },
      { label: '강사근태현황' },
      { label: '팀별 퇴원율' },
      { label: '팀별 강사 등급' },
      { label: '퇴사강사현황' },
      { label: '센터별 강사 근태현황' },
      { label: '상담매니저별 월 수강율' },
      { label: '상담매니저별 일일 수강율' },
      { label: '월별 학습매니져 상담건수' },
      { label: '일별 학습매니져 상담건수' },
      { label: '무료체험 진행현황' },
      { label: '강사별 LAT 성공율' },
    ],
  },
  {
    key: 'control-system',
    label: '관제시스템',
    icon: '📈',
    children: [
      { label: '4month Score' },
      { label: 'Tutor Monitoring' },
      { label: 'PIP Monitoring' },
      { label: 'Attendance Monitoring' },
      { label: 'Dropped tutors' },
      { label: 'New tutor evaluation monitor' },
      { label: 'Best LAT Tutor' },
    ],
  },
  {
    key: 'operation-board',
    label: '운영게시판',
    icon: '👥',
    children: [
      { label: '한국직원 게시판' },
      { label: '강사소통 게시판' },
      { label: '유입접속통계' },
      { label: '메인이벤트이미지관리' },
      { label: '제휴문의' },
      { label: '제휴문의(Old)' },
      { label: '공휴일지정' },
      { label: '휴강관리' },
      { label: 'SMS 문자관리' },
      { label: 'LMS 문자관리' },
      { label: '알림톡 문자관리' },
      { label: '발송문자함관리' },
      { label: '단체 SMS 발송함 관리' },
      { label: '설문/평가관리' },
      { label: '메인팝업관리' },
      { label: '강사팝업관리' },
      { label: '무료체험회원평가관리' },
      { label: 'LMS 접속허용 아이피관리' },
      { label: '후기 비디오관리' },
      { label: '이미지 팝업관리' },
      { label: 'Story Writing 과제관리' },
    ],
  },
  {
    key: 'tuition',
    label: '수강료관리',
    icon: '💳',
    children: [{ label: '일일정산달력' }, { label: '결제내역확인' }, { label: '일일수강정산통계' }, { label: '월수강정산통계' }],
  },
  {
    key: 'tutor-manage',
    label: '강사관리',
    icon: '💳',
    children: [
      { label: 'Applicant date' },
      { label: '강사리스트' },
      { label: '신규강사리스트' },
      { label: '강사그룹관리' },
      { label: '강사우선순위' },
      { label: '강사지원현황' },
      { label: 'Today Attendance list' },
      { label: '강사 퇴사, 입사 통계' },
      { label: '강사 채용 추천 통계' },
      { label: '콜센터관리' },
      { label: 'LAT 강사성향평가관리' },
    ],
  },
  {
    key: 'hr',
    label: '직원&HR 관리',
    icon: '🪪',
    children: [
      { label: '해외직원관리' },
      { label: '한국직원관리' },
      { label: '수강매니저 휴일등록관리' },
      { label: '직원 출결확인' },
      { label: '캐릭터관리' },
    ],
  },
  {
    key: 'epayment',
    label: '전자결제',
    icon: '🪪',
    children: [{ label: '교육매뉴얼관리' }],
  },
  {
    key: 'class-stats',
    label: '수강통계',
    icon: '📊',
    children: [
      { label: '수강통계' },
      { label: '강사체험통계' },
      { label: '매니저체험통계' },
      { label: '강사등급및수급통계' },
      { label: 'Tutor list in storybook class' },
      { label: 'LAT 회원평가' },
      { label: 'LAT 미수강 통계' },
      { label: 'LAT 시간/요일별 통계' },
    ],
  },
  {
    key: 'tutor-eval-stats',
    label: '강사 평가통계',
    icon: '📈',
    children: [
      { label: 'Tutor Assessment' },
      { label: 'All Tutor Assessment' },
      { label: 'Four month score' },
      { label: '4MS 누락 데이타 검증' },
      { label: 'Working hour record' },
      { label: 'Quit student number' },
      { label: 'LAT success rate' },
      { label: 'Tutor Category' },
      { label: 'Grade & PIP' },
      { label: 'CQR 학습매니저 통계' },
      { label: 'Grade Management' },
      { label: 'C.Q.R Assessment' },
      { label: 'Monthly Attendance list' },
      { label: 'Total Working Hour' },
    ],
  },
  {
    key: 'trainer-eval-stats',
    label: '트레이너 평가통계',
    icon: '📉',
    children: [{ label: '강사보유현황' }, { label: '우수강사보유현황' }],
  },
  {
    key: 'manager-eval-stats',
    label: '학습매니저 평가통계',
    icon: '📉',
    children: [
      { label: '평가통계표' },
      { label: '학생보유현황' },
      { label: '우수강사보유현황' },
      { label: '특강수업 수강생확인' },
      { label: '평가용 설문관리' },
      { label: '회원대상 평가통계' },
      { label: '부정상담 리스트' },
    ],
  },
  {
    key: 'edu-product',
    label: '교육상품관리',
    icon: '🗂️',
    children: [
      { label: '결제팝업 노출 관리' },
      { label: '결합상품관리' },
      { label: '수강신청/수강료안내' },
      { label: '추가 학습 상품 관리' },
      { label: 'M.E레벨관리' },
      { label: '교재상품관리' },
      // 실제로 동작하는 화면 3개. "교재상품관리" 항목 바로 아래에 배치한다.
      { key: 'payment-check', label: '교재 주문 대시보드', path: '/payment-check' },
      { key: 'order-management', label: '교재주문/재고관리', path: '/order-management' },
      { key: 'cancel-return', label: '주문취소/반품관리', path: '/cancel-return' },
      { key: 'naver-events', label: '네이버 이벤트 주문건', path: '/naver-events' },
      { label: '추가 결제 및 부분 환불 관리' },
      { label: '카드/실시간/무통장 결제확인 - 영구보관' },
      { label: '아이딕 잉글리쉬 상품관리' },
      { label: '아이딕 잉글리쉬 결제확인' },
      { label: '아이딕 홈스쿨 결제확인' },
      { label: '리딩 스쿨 결제확인' },
    ],
  },
  {
    key: 'community',
    label: '커뮤니티관리',
    icon: '💬',
    children: [{ label: '게시판관리' }, { label: '게시판추가' }, { label: '게시물추적' }],
  },
  {
    key: 'test-paper',
    label: '테스트페이퍼관리',
    icon: '📗',
    children: [{ label: '테스트문제관리' }, { label: '테스트결과' }],
  },
  {
    key: 'message-box',
    label: '쪽지함관리',
    icon: '✉️',
    children: [{ label: '받은 쪽지함' }, { label: '보낸 쪽지함' }],
  },
  {
    key: 'database',
    label: 'Data Base관리',
    icon: '💾',
    children: [{ label: 'DB 상태보기' }, { label: 'DB백업' }],
  },
  {
    key: 'base-config',
    label: '기본설정',
    icon: '⚙️',
    children: [{ label: '기본정보' }, { label: '관리자설정' }, { label: '거래은행설정' }],
  },
  { key: 'info-modify', label: 'Info Modify', icon: '🪪' },
  {
    key: 'class-room',
    label: 'Class Room',
    icon: '🖥️',
    children: [
      { label: 'Meeting room' },
      { label: '강의실관리' },
      { label: 'Class Room Moniter' },
      { label: 'Applicant Room' },
      { label: 'ZOOM Class Room' },
      { label: 'Test Room' },
    ],
  },
  { key: 'video-upload', label: '수업영상 등록', icon: '🎥' },
]
